### PR TITLE
long_call / far and near attributes

### PR DESCRIPTION
**Pull request by LeChuck42**
I added the possibility to define functions as far and so force the compiler to emit l.jr instructions for their calls.
See mailinglist openrisc@lists.opencores.org

### CODE REVIEW

**Comment by jeremybennett** [comment]
Hi LeChuck42,
Thanks for the contribution.  I'm not so active now, so I'll let others comment on the technical content.
I see a couple of things missing.  You don't have an update to the ChangeLog and you need to update the OpenRISC specific part of the manual.

**Comment by suelin** [comment]
Hi, my name is Suelin and I'm a student and a beginner of this. 
I'm trying to use the code present on or1k-support.h, about the timer, the first example, can you confirm for mi if that code is working well?

**Comment by jeremybennett** [comment]
suelin - I suggest you ask these questions on one of the OpenRISC mailing lists or IRC.  As fas as I know this code is good, but if you need advice, someone there should be able to help.  See http://opencores.org/or1k/OR1K:Community_Portal#Mailing_lists

**Comment by suelin** [comment]
Hi jeremybennett, thank you for help me, just one more question that you, maybe know about it.
Do you know if the code works for a Digilent atlys board?

**Comment by wallento** [comment]
If you run OpenRISC on it, it should work ;) Please use the mailing list for such questions, this is for actual technical discussion about the issue..

**Comment by stffrdhrn** [comment]
I am closing this I cannot se the original commit, and this is before the rewrite. Please re-open if this is still an issue after the rewrite.

**Pull request closed without merging**
